CREATE TABLE IF NOT EXISTS placement_stats (
  id INT AUTO_INCREMENT PRIMARY KEY,
  academic_year VARCHAR(20) NOT NULL,
  company_name VARCHAR(255) NOT NULL,
  role_name VARCHAR(255) NOT NULL,
  students_placed INT NOT NULL DEFAULT 0,
  package_lpa DECIMAL(10,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS historical_analytics (
  id INT AUTO_INCREMENT PRIMARY KEY,
  year_label VARCHAR(20) NOT NULL,
  total_students INT NOT NULL DEFAULT 0,
  total_placed INT NOT NULL DEFAULT 0,
  highest_package DECIMAL(10,2) NOT NULL DEFAULT 0,
  average_package DECIMAL(10,2) NOT NULL DEFAULT 0,
  metadata JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
